### PR TITLE
Fire event fix

### PR DESCRIPTION
**Pull request by wouterz**
fix fire events to work. If statement used an unset integer, so was always value 0, which made 2 buttons not function at all.

### CODE REVIEW

**Comment by jessetilro** [comment]
Nice work. There's some duplication of code, can you fix this while you're at it? I mean taking the accumulation verification and putting it into a single method.

**Comment by dalderliesten** [comment]
Looks good to me.

**Comment by jessetilro** [comment]
LGTM

**Comment by dalderliesten** [comment]
Considering I'm gonna change the fire event based on the feedback, don't wait.

**Pull request merged**
