### PR TITLE
Refactor event synchronization

### PR DESCRIPTION
**Pull request by jessetilro**
Refactored the entire network messaging system. All Event validation is done server-side now. In short this has two benefits:
- Increase of maintainability because of less shared components between client and server.
- Fixes bug described in the issue referenced below (227).

Developed (and should therefore be tested) in parallel with PR https://github.com/jessetilro/pixelperfect/pull/236.
Resolves Issues https://github.com/jessetilro/pixelperfect/issues/227, https://github.com/jessetilro/pixelperfect/issues/226 and https://github.com/jessetilro/pixelperfect/issues/224.

### CODE REVIEW

**Comment by dalderliesten** [comment]
You forgot to remove/alter the test suite.

**Comment by jessetilro** [comment]
@dalderliesten Thanks, I was already on it. I hope it is fixed now. Let's wait and see what Travis thinks about it.

**Comment by dalderliesten** [comment]
Yep, approved!

**Comment by wouterz** [comment]
thats a lot of useless LOC, goodjob!

**Pull request merged**
