### PR TITLE
added code to send RoleChosenMessages

### PR DESCRIPTION
**Pull request by dmalarev**
It should now send the messages to server when a role is chosen

### CODE REVIEW

**Comment by FlXlT** [comment]
LGTM, let's test it manually.

**Comment by FlXlT** [comment]
Still contains a bug. I suggest to close this PR and delete the branch for now.

**Comment by dmalarev** [comment]
Alright, sounds good

**Comment by jessetilro** [comment]
This will have to be reopened when the bug is fixed.

**Pull request closed without merging**
